# Generated by Django 2.0.3 on 2018-03-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_inventory_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateField(),
        ),
    ]
