# Generated by Django 2.0.3 on 2018-04-12 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20180330_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
